[package]
name = "budgetaar-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
duckdb = { version = "1.1.1", features = ["bundled", "chrono", "json"] }
iban_validate = "5.0.1"
